### ISSUE TITLE
How to use this service with AWS SES (Simple Email Service)?

### ISSUE THREAD

**Issue by styxlab** [mhart/aws4fetch#40]
I've tried to use this service to connect to AWS SES but without any luck, for example:

```
const region = 'us-east-1'
const aws = new AwsClient({ accessKeyId: SES_AWS_ACCESS_KEY_ID, secretAccessKey: SES_AWS_SECRET_ACCESS_KEY })
await aws.fetch(`https://email.${region}.amazonaws.com`, { body: { from, to, subject, text }})
```

But I get a 4xx status code. Any help would be appriciated.

**Comment by obieq** [comment]
At quick glance, the problem is most likely due to the fact that, in your example, there's no REST endpoint specified.

per AWS' docs, if you're trying to send an email, then your request has to conform to: https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_SendEmail.html

so, `https://email.${region}.amazonaws.com` becomes `https://email.${region}.amazonaws.com/v2/email/outbound-emails`
also, your body content needs to change as well (per the docs)

**Comment by styxlab** [comment]
Thanks for looking into this issue! I now got it to work with the mentioned AWS docs! Thanks so much for this nice package!
